"""followers

Revision ID: 932b851c21c8
Revises: bd54c7ef2017
Create Date: 2020-05-06 16:08:56.432569

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '932b851c21c8'
down_revision = 'bd54c7ef2017'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('followers',
    sa.Column('follower_id', sa.Integer(), nullable=True),
    sa.Column('followed_id', sa.Integer(), nullable=True),
    sa.ForeignKeyConstraint(['followed_id'], ['user.id'], ),
    sa.ForeignKeyConstraint(['follower_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('followers')
    # ### end Alembic commands ###
